### ISSUE TITLE
Currently maniac isn't working

### ISSUE THREAD

**Issue by Twiston-7** [fs-c/maniac#82]
thats about it

**Comment by fs-c** [comment]
I should have some time to look into it next week. In the meantime, PRs welcome ;)

**Comment by fs-c** [comment]
I have a very temporary fix but I want to take some time to make the solution more robust. The issue is the map player signature, which has already been broken earlier this year. I will move away from reading hitpoints from memory and just read them from the corresponding beatmap file.

I'm doing this to prevent maniac from failing in all cases (like it does right now), but it might make it a little more unstable in corner cases for specific maps. I'm currently still working on reducing the instability to a minimum.

**Comment by fs-c** [comment]
I couldn't get the solution I had in mind to work consistently (yet), so I just fixed the breaking offset.
